# Generated by Django 2.2.2 on 2019-06-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('dogId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dogName', models.CharField(max_length=30)),
                ('dogBreed', models.CharField(max_length=30)),
                ('dogAge', models.CharField(max_length=30)),
                ('ownerId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('investorId', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=30)),
                ('num_of_shares', models.IntegerField()),
                ('purch_price', models.IntegerField()),
                ('current_val', models.IntegerField()),
                ('purch_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerFName', models.CharField(max_length=30)),
                ('ownerLName', models.CharField(max_length=30)),
                ('ownerId', models.ManyToManyField(to='dogstock.Owners')),
            ],
        ),
    ]
